### ISSUE TITLE
Visualization bug in QNames

### ISSUE THREAD

**Issue by storress** [niclabs/ratadns-remy#22]
Threads that connect blocks, doesn't follow a block when that block is moved
![captura de pantalla 2016-08-31 a las 4 25 05 p m](https://cloud.githubusercontent.com/assets/9119756/18143229/8f9fb180-6f97-11e6-84a9-ad7c07afece9.png)

**Comment by storress** [comment]
There is no point in allowing drag and move in this visualization, because is updated in Real Time so, when the visualization updates, all blocks go back to their original position.

Now, it's not possible to drag and move blocks

Fixed by https://github.com/niclabs/ratadns-remy/commit/8842e61711747fcfd32bb3ceb4bdf561a5417fa1

**Comment by camilog** [comment]
can we change the cursor?
currently still shows the cursor with the ability to drag&drop the boxes, can we change it to just a nomal cursor?
